"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import uploaded_file
from insta485.views.user import show_user
from insta485.views.user import follow_unfollow_user
from insta485.views.user import logout
from insta485.views.followers import show_followers
from insta485.views.following import show_following
from insta485.views.post import show_post
from insta485.views.post import create_delete_post
from insta485.views.explore import explore
from insta485.views.login import login
from insta485.views.create import create
from insta485.views.likes import likes_unlike
from insta485.views.comments import add_delete_comments
from insta485.views.delete import delete
from insta485.views.edit import edit
from insta485.views.accounts import account_operation
from insta485.views.password import password
from insta485.views.auth import auth_check
